name: CPFix
main: fromgate.cpfix.CPFix
version: 0.3.2
author: fromgate, fromgate@gmail.com
commands:
   cpfix:
      description: Show settings of plugin (or reloads configuration)
      usage: |
           /cpfix - show configuration
           /cpfix reload - reload configuration
           /cpfix auto - perform automatic configuration